/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.recuperacionignacio;

import DAOs.DAOJugador;
import Errores.ErrorCuadroVacio;
import Errores.ErrorNoDatos;
import POJOs.Jugador;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dam
 */
public class PantallaJugadores extends javax.swing.JFrame {
    
    DAOs.DAOJugador daoJugador;
    List<String> consultasRealizadas = new ArrayList<>();

    /**
     * Creates new form PantallaJugadores
     */
    public PantallaJugadores() {
        initComponents();
        
        daoJugador = new DAOJugador();
        
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Dorsal");
        modelo.addColumn("Nombre");
        modelo.addColumn("Puntos");
        modelo.addColumn("Rebotes");
        modelo.addColumn("Asistencias");
        
        tableJugadores.setModel(modelo);
        
        cargarListaConsultas();
    }
    
    public PantallaJugadores(DAOJugador daoJugador) {
        this.daoJugador = daoJugador;
    }
    
    public void cargarTablaJugadores(List<Jugador> jugadores) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Dorsal");
            modelo.addColumn("Nombre");
            modelo.addColumn("Puntos");
            modelo.addColumn("Rebotes");
            modelo.addColumn("Asistencias");

            Object[] registroLeido = new Object[5];

            for (Jugador jugador : jugadores) {
                registroLeido[0] = jugador.getDorsal();
                registroLeido[1] = jugador.getNombre();
                registroLeido[2] = jugador.getPuntos();
                registroLeido[3] = jugador.getRebotes();
                registroLeido[4] = jugador.getAsistencias();

                modelo.addRow(registroLeido);
            }

            tableJugadores.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void cargarListaConsultas() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
            
        for (String consulta : consultasRealizadas) {
            listModel.addElement(consulta);
        }
            
        lstConsultas.setModel(listModel);
    }
    
    public List<Jugador> contarAnotadores(int puntos) {
        List<Jugador> jugadores = daoJugador.getJugadores();
        List<Jugador> jugadoresFiltrados = new ArrayList<>();
        
        jugadores.stream().filter(jugador -> jugador.getPuntos() > puntos).forEach((jugador -> jugadoresFiltrados.add(jugador)));
        
        return jugadoresFiltrados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJugadores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstConsultas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consulta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableJugadores);

        lstConsultas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstConsultasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String consulta = txtConsulta.getText();
        
            if (consulta.isEmpty()) {
                throw new ErrorCuadroVacio();
            } else {
                List<Jugador> jugadores = new ArrayList<>();
                
                if (consulta.contains("puntos ")) {
                    int puntos = Integer.parseInt(consulta.substring(7));
                    jugadores = contarAnotadores(puntos);
                } else {
                    jugadores = daoJugador.realizarConsulta(consulta);
                }
                
                if (jugadores.isEmpty()) {
                    throw new ErrorNoDatos();
                } else {
                    if (!consultasRealizadas.contains(consulta)) {
                        consultasRealizadas.add(consulta);
                    }
                    cargarListaConsultas();
                    cargarTablaJugadores(jugadores);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtConsulta.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void lstConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstConsultasMouseClicked
        String consultaSeleccionada = lstConsultas.getSelectedValue();
        
        if (!consultaSeleccionada.isEmpty()) {
            txtConsulta.setText(consultaSeleccionada);
        }
    }//GEN-LAST:event_lstConsultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstConsultas;
    private javax.swing.JTable tableJugadores;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
